### ISSUE TITLE
添加 type of change 快速列表显示数量设置

### ISSUE THREAD

**Issue by TheLastSunset** [fobgochod/git-commit-message-format#11]
默认为 3，可自定义显示数量
![image](https://github.com/fobgochod/git-commit-message-format/assets/88444633/1cbde037-8935-48d5-b68b-f0c3ed944448)

**Comment by fobgochod** [comment]
![image](https://github.com/fobgochod/git-commit-message-format/assets/13817644/d2e1013e-10e7-47a3-b50f-6b4d6f50f066)

点右下角小扳手图标，或者Settings->Tools->Git Commit Message 里面可以设定默认数量

**Comment by fobgochod** [comment]
> 默认为 3，可自定义显示数量 ![image](https://private-user-images.githubusercontent.com/88444633/290392057-1cbde037-8935-48d5-b68b-f0c3ed944448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NTUwNTUsIm5iZiI6MTcwMzY1NDc1NSwicGF0aCI6Ii84ODQ0NDYzMy8yOTAzOTIwNTctMWNiZGUwMzctODkzNS00OGQ1LWI2OGItZjBjM2VkOTQ0NDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA1MjU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZWI3YjY5ZDljZDM4ZGY4YzFiZWY1Y2M0MDE0ZWUzMzk5ZmIyMTE5NzUxOWY3MjQ4MzQwMzkyNWRhODRlNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nf2Foku1AMSbJwB_rr81hrFXAJdF6IjM03xc8qu9JI0)

![image](https://github.com/fobgochod/git-commit-message-format/assets/13817644/d2e1013e-10e7-47a3-b50f-6b4d6f50f066)

点右下角小扳手图标，或者Settings->Tools->Git Commit Message 里面可以设定默认数量

**Comment by fobgochod** [comment]
![image](https://github.com/fobgochod/git-commit-message-format/assets/13817644/d2e1013e-10e7-47a3-b50f-6b4d6f50f066)

点右下角小扳手图标，或者Settings->Tools->Git Commit Message 里面可以设定默认数量

**Comment by TheLastSunset** [comment]
好的，谢谢
