### ISSUE TITLE
72个字符换行格式化处理相关问题

### ISSUE THREAD

**Issue by huo-feng-ding** [fobgochod/git-commit-message-format#6]
当我写了一长段body内容，勾选了 72个字符换行处理，后格式化成下边的情况
![image](https://github.com/fobgochod/git-commit-message-format/assets/3919535/38ea7881-7853-4b2d-9682-b6004b5db9d2)

然后我再点开 Create Commit Message 对话框，再点“OK”，字符格式化又变了
![image](https://github.com/fobgochod/git-commit-message-format/assets/3919535/3c5d874f-892a-4f5d-9988-8af8aa641649)

**Comment by huo-feng-ding** [comment]
请问可以修复吗

**Comment by fobgochod** [comment]
> 请问可以修复吗

2.0.6修复

**Comment by fobgochod** [comment]
e9d2d16d9091cbdc6a66fc02bb43c696ffb1383c

**Comment by fobgochod** [comment]
e9d2d16d9091cbdc6a66fc02bb43c696ffb1383c
